#!/usr/bin/env python3
"""Generate simplified, physics-friendly collision geometry for gz-sim models.

A visual mesh exported from CAD is often far too dense (the f450 body is ~260k
faces) and concave, so using it directly as a Gazebo collision makes physics lag.
This tool runs CoACD convex decomposition on the mesh and writes a small set of
convex sub-meshes plus the matching SDF ``<collision>`` block. Each part is convex,
so the physics engine handles it cheaply and correctly — unlike a single concave
mesh, and unlike a single convex hull (which would fill the gaps between an
X-frame's arms).

Example (f450 body, baking in the visual pose so collision aligns with the model):

    ./gen_collision.py --model f450_base --link base_link \
        --transform "0 0 0.02 0 0 -0.125861774" \
        --threshold 0.05 --min-volume 1e-5

Add ``--apply`` to replace the marked collision block inside the model's
``model.sdf`` in place (idempotent — re-running updates the same block).

Dependencies: trimesh, coacd, numpy (see requirements.txt).
"""

from __future__ import annotations

import argparse
import math
import re
import sys
from pathlib import Path

import numpy as np
import trimesh


# ---------------------------------------------------------------------------
# Geometry helpers
# ---------------------------------------------------------------------------
def _rpy_matrix(x, y, z, roll, pitch, yaw):
    """Build a 4x4 transform from an SDF-style ``x y z R P Y`` pose (radians)."""
    cr, sr = math.cos(roll), math.sin(roll)
    cp, sp = math.cos(pitch), math.sin(pitch)
    cy, sy = math.cos(yaw), math.sin(yaw)
    rx = np.array([[1, 0, 0], [0, cr, -sr], [0, sr, cr]])
    ry = np.array([[cp, 0, sp], [0, 1, 0], [-sp, 0, cp]])
    rz = np.array([[cy, -sy, 0], [sy, cy, 0], [0, 0, 1]])
    m = np.eye(4)
    m[:3, :3] = rz @ ry @ rx
    m[:3, 3] = [x, y, z]
    return m


def parse_transform(text):
    if not text:
        return None
    vals = [float(v) for v in text.replace(",", " ").split()]
    if len(vals) != 6:
        raise ValueError("--transform needs 6 numbers: 'x y z R P Y'")
    return _rpy_matrix(*vals)


def decompose(mesh, *, threshold, preprocess_resolution, max_convex_hull,
              max_ch_vertex, seed):
    """Run CoACD and return a list of convex trimesh parts."""
    import coacd

    coacd.set_log_level("error")
    cmesh = coacd.Mesh(np.asarray(mesh.vertices), np.asarray(mesh.faces))
    parts = coacd.run_coacd(
        cmesh,
        threshold=threshold,
        max_convex_hull=max_convex_hull,
        preprocess_mode="auto",
        preprocess_resolution=preprocess_resolution,
        max_ch_vertex=max_ch_vertex,
        merge=True,
        seed=seed,
    )
    out = []
    for verts, faces in parts:
        part = trimesh.Trimesh(vertices=np.asarray(verts),
                               faces=np.asarray(faces), process=True)
        if part.is_empty or len(part.faces) == 0:
            continue
        # convex_hull guarantees a clean convex shape with a low face count
        out.append(part.convex_hull)
    return out


def fit_boxes(mesh, *, split_z, n_legs, leg_offset, leg_min_pts):
    """x500-style box fit: one AABB 'body' box over the upper structure, plus one
    AABB box per landing-leg cluster below ``split_z`` (legs split into ``n_legs``
    angular sectors). Returns a list of (name, center[3], size[3])."""
    v = np.asarray(mesh.vertices)
    boxes = []
    upper = v[v[:, 2] >= split_z]
    if len(upper):
        lo, hi = upper.min(0), upper.max(0)
        boxes.append(("body", (lo + hi) / 2.0, hi - lo))
    lower = v[v[:, 2] < split_z]
    if len(lower) and n_legs > 0:
        ang = np.arctan2(lower[:, 1], lower[:, 0])
        sect = np.floor(((ang + leg_offset) % (2 * np.pi)) /
                        (2 * np.pi / n_legs)).astype(int)
        legs = []
        for s in range(n_legs):
            c = lower[sect == s]
            if len(c) < leg_min_pts:
                continue
            lo, hi = c.min(0), c.max(0)
            legs.append(((lo + hi) / 2.0, hi - lo))
        # name legs by descending size so they're stable/readable
        for i, (ctr, size) in enumerate(legs):
            boxes.append((f"leg{i}", ctr, size))
    return boxes


# ---------------------------------------------------------------------------
# SDF emission
# ---------------------------------------------------------------------------
def collision_block(link, parts, mesh_uris):
    begin = f"      <!-- BEGIN gen-collision:{link} -->"
    end = f"      <!-- END gen-collision:{link} -->"
    lines = [begin]
    lines.append("      <!-- Auto-generated by tools/collision/gen_collision.py "
                 "(CoACD convex decomposition). Do not hand-edit between markers. -->")
    for i, uri in enumerate(mesh_uris):
        lines += [
            f'      <collision name="{link}_col_{i:02d}">',
            "        <geometry>",
            "          <mesh>",
            "            <scale>1 1 1</scale>",
            f"            <uri>{uri}</uri>",
            "          </mesh>",
            "        </geometry>",
            "        <surface>",
            "          <contact>",
            "            <ode>",
            "              <min_depth>0.001</min_depth>",
            "              <max_vel>0</max_vel>",
            "            </ode>",
            "          </contact>",
            "          <friction>",
            "            <ode/>",
            "          </friction>",
            "        </surface>",
            "      </collision>",
        ]
    lines.append(end)
    return "\n".join(lines)


def box_collision_block(link, boxes):
    begin = f"      <!-- BEGIN gen-collision:{link} -->"
    end = f"      <!-- END gen-collision:{link} -->"
    lines = [begin,
             "      <!-- Auto-generated by tools/collision/gen_collision.py "
             "(box fit). Do not hand-edit between markers. -->"]
    for i, (name, ctr, size) in enumerate(boxes):
        cx, cy, cz = (round(float(x), 4) for x in ctr)
        sx, sy, sz = (round(float(x), 4) for x in size)
        lines += [
            f'      <collision name="{link}_col_{i:02d}_{name}">',
            f"        <pose>{cx} {cy} {cz} 0 0 0</pose>",
            "        <geometry>",
            f"          <box><size>{sx} {sy} {sz}</size></box>",
            "        </geometry>",
            "        <surface>",
            "          <contact>",
            "            <ode>",
            "              <min_depth>0.001</min_depth>",
            "              <max_vel>0</max_vel>",
            "            </ode>",
            "          </contact>",
            "          <friction>",
            "            <ode/>",
            "          </friction>",
            "        </surface>",
            "      </collision>",
        ]
    lines.append(end)
    return "\n".join(lines)


def apply_block(sdf_path, link, block):
    """Replace (or insert) the marked collision block for ``link`` in model.sdf."""
    text = sdf_path.read_text()
    begin = re.escape(f"<!-- BEGIN gen-collision:{link} -->")
    end = re.escape(f"<!-- END gen-collision:{link} -->")
    pattern = re.compile(r"[ \t]*" + begin + r".*?" + end, re.DOTALL)
    if pattern.search(text):
        new = pattern.sub(lambda _: block, text, count=1)
        action = "replaced"
    else:
        # Insert just before the closing </link> of the named link.
        link_open = re.search(rf'<link\s+name=[\'"]{re.escape(link)}[\'"]', text)
        if not link_open:
            raise SystemExit(f"link '{link}' not found in {sdf_path}")
        close = text.find("</link>", link_open.end())
        if close == -1:
            raise SystemExit(f"no </link> after link '{link}' in {sdf_path}")
        new = text[:close] + block + "\n    " + text[close:]
        action = "inserted"
    sdf_path.write_text(new)
    return action


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--models-dir", default=str(Path(__file__).resolve().parents[2] / "models"),
                    help="Path to the gz models/ directory (default: repo models/).")
    ap.add_argument("--model", required=True, help="Model folder name, e.g. f450_base.")
    ap.add_argument("--link", required=True, help="Link name the collisions belong to.")
    ap.add_argument("--mesh", help="Mesh file under <model>/meshes/ "
                    "(default: first *.STL/*.stl/*.dae/*.obj found).")
    ap.add_argument("--transform", help="Bake an SDF pose 'x y z R P Y' (radians) "
                    "into the collision so it matches the visual.")
    ap.add_argument("--method", choices=("box", "coacd"), default="box",
                    help="box: x500-style body + leg boxes (light, rests on ground). "
                    "coacd: convex decomposition of the full mesh. Default box.")
    # box-method options
    ap.add_argument("--split-z", type=float,
                    help="[box] z (model frame) splitting upper body from landing legs. "
                    "Verts >= split-z become one body box; verts below are clustered "
                    "into legs. Required for --method box.")
    ap.add_argument("--n-legs", type=int, default=4,
                    help="[box] number of landing-leg clusters below split-z. Default 4.")
    ap.add_argument("--leg-offset", type=float, default=0.0,
                    help="[box] angular offset (rad) for leg sector clustering. Default 0.")
    ap.add_argument("--leg-min-pts", type=int, default=30,
                    help="[box] drop leg clusters with fewer vertices than this. Default 30.")
    ap.add_argument("--threshold", type=float, default=0.05,
                    help="CoACD concavity threshold (0.01 fine .. 1 coarse). Default 0.05.")
    ap.add_argument("--min-volume", type=float, default=1e-5,
                    help="Drop convex parts whose volume (m^3) is below this. Default 1e-5.")
    ap.add_argument("--preprocess-resolution", type=int, default=50)
    ap.add_argument("--max-convex-hull", type=int, default=-1,
                    help="Cap number of convex parts (-1 = unlimited).")
    ap.add_argument("--max-ch-vertex", type=int, default=64,
                    help="Max vertices per convex hull. Default 64.")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--apply", action="store_true",
                    help="Replace the marked collision block in model.sdf in place.")
    ap.add_argument("--dry-run", action="store_true",
                    help="Decompose and report, but write no files.")
    args = ap.parse_args(argv)

    model_dir = Path(args.models_dir) / args.model
    mesh_dir = model_dir / "meshes"
    if not model_dir.is_dir():
        raise SystemExit(f"model dir not found: {model_dir}")

    if args.mesh:
        mesh_path = mesh_dir / args.mesh
    else:
        cands = [p for ext in ("*.STL", "*.stl", "*.dae", "*.obj")
                 for p in sorted(mesh_dir.glob(ext))]
        if not cands:
            raise SystemExit(f"no mesh found under {mesh_dir}")
        mesh_path = cands[0]
    if not mesh_path.is_file():
        raise SystemExit(f"mesh not found: {mesh_path}")

    mesh = trimesh.load(mesh_path, force="mesh")
    src_faces = len(mesh.faces)
    tf = parse_transform(args.transform)
    if tf is not None:
        mesh = mesh.copy()
        mesh.apply_transform(tf)

    sdf_path = model_dir / "model.sdf"

    # -------------------------------------------------------------------
    # Box method: x500-style body + leg boxes. No mesh files, just SDF boxes.
    # -------------------------------------------------------------------
    if args.method == "box":
        if args.split_z is None:
            raise SystemExit("--method box needs --split-z (body/leg z boundary).")
        boxes = fit_boxes(mesh, split_z=args.split_z, n_legs=args.n_legs,
                          leg_offset=args.leg_offset, leg_min_pts=args.leg_min_pts)
        if not boxes:
            raise SystemExit("box fit produced no boxes; check --split-z.")
        lowest = min(float(c[2] - s[2] / 2.0) for _, c, s in boxes)
        names = ", ".join(n for n, _, _ in boxes)
        print(f"[*] {mesh_path.name}: {len(boxes)} boxes [{names}]; "
              f"lowest collision z = {lowest:.4f} (model rests at base_link "
              f"z = {-lowest:.4f}).", file=sys.stderr)
        block = box_collision_block(args.link, boxes)
        if args.dry_run:
            print(block)
            return 0
        if args.apply:
            action = apply_block(sdf_path, args.link, block)
            print(f"[*] {action} gen-collision block for '{args.link}' "
                  f"in {args.model}/model.sdf", file=sys.stderr)
        else:
            print("\n# --- paste between the <link> tags, or re-run with --apply ---\n")
            print(block)
        return 0

    print(f"[*] {mesh_path.name}: {src_faces} faces -> CoACD "
          f"(threshold={args.threshold}) ...", file=sys.stderr)
    parts = decompose(
        mesh,
        threshold=args.threshold,
        preprocess_resolution=args.preprocess_resolution,
        max_convex_hull=args.max_convex_hull,
        max_ch_vertex=args.max_ch_vertex,
        seed=args.seed,
    )
    parts = [p for p in parts if p.volume >= args.min_volume]
    if not parts:
        raise SystemExit("CoACD produced no parts above --min-volume; lower it.")
    total_faces = sum(len(p.faces) for p in parts)
    print(f"[*] {len(parts)} convex parts, {total_faces} faces total "
          f"({src_faces / max(total_faces,1):.0f}x lighter).", file=sys.stderr)

    stem = mesh_path.stem
    out_dir = mesh_dir / "collision"
    uris, rel_paths = [], []
    for i, part in enumerate(parts):
        rel = f"meshes/collision/{stem}_col_{i:02d}.stl"
        uris.append(f"model://{args.model}/{rel}")
        rel_paths.append(out_dir / f"{stem}_col_{i:02d}.stl")

    block = collision_block(args.link, parts, uris)

    if args.dry_run:
        print(block)
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    # Remove stale parts from a previous run so a lower part count leaves no orphans.
    stale = [p for p in out_dir.glob(f"{stem}_col_*.stl") if p not in rel_paths]
    for p in stale:
        p.unlink()
    for part, path in zip(parts, rel_paths):
        part.export(path)
    msg = f"[*] wrote {len(parts)} STL parts to {out_dir}"
    if stale:
        msg += f" (removed {len(stale)} stale)"
    print(msg, file=sys.stderr)

    if args.apply:
        action = apply_block(model_dir / "model.sdf", args.link, block)
        print(f"[*] {action} gen-collision block for '{args.link}' "
              f"in {args.model}/model.sdf", file=sys.stderr)
    else:
        print("\n# --- paste between the <link> tags, or re-run with --apply ---\n")
        print(block)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
